/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HandpanClassesRouteImport } from './routes/handpan-classes'
import { Route as SoundHealingInitiationRouteImport } from './routes/sound-healing-initiation'
import { Route as SoundHealingSessionsRouteImport } from './routes/sound-healing-sessions'
import { Route as WellnessRetreatsRouteImport } from './routes/wellness-retreats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HandpanClassesRoute = HandpanClassesRouteImport.update({
  id: '/handpan-classes',
  path: '/handpan-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundHealingInitiationRoute = SoundHealingInitiationRouteImport.update({
  id: '/sound-healing-initiation',
  path: '/sound-healing-initiation',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundHealingSessionsRoute = SoundHealingSessionsRouteImport.update({
  id: '/sound-healing-sessions',
  path: '/sound-healing-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRetreatsRoute = WellnessRetreatsRouteImport.update({
  id: '/wellness-retreats',
  path: '/wellness-retreats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/handpan-classes': typeof HandpanClassesRoute
  '/sound-healing-initiation': typeof SoundHealingInitiationRoute
  '/sound-healing-sessions': typeof SoundHealingSessionsRoute
  '/wellness-retreats': typeof WellnessRetreatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/handpan-classes': typeof HandpanClassesRoute
  '/sound-healing-initiation': typeof SoundHealingInitiationRoute
  '/sound-healing-sessions': typeof SoundHealingSessionsRoute
  '/wellness-retreats': typeof WellnessRetreatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/handpan-classes': typeof HandpanClassesRoute
  '/sound-healing-initiation': typeof SoundHealingInitiationRoute
  '/sound-healing-sessions': typeof SoundHealingSessionsRoute
  '/wellness-retreats': typeof WellnessRetreatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/handpan-classes'
    | '/sound-healing-initiation'
    | '/sound-healing-sessions'
    | '/wellness-retreats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/handpan-classes'
    | '/sound-healing-initiation'
    | '/sound-healing-sessions'
    | '/wellness-retreats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/handpan-classes'
    | '/sound-healing-initiation'
    | '/sound-healing-sessions'
    | '/wellness-retreats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HandpanClassesRoute: typeof HandpanClassesRoute
  SoundHealingInitiationRoute: typeof SoundHealingInitiationRoute
  SoundHealingSessionsRoute: typeof SoundHealingSessionsRoute
  WellnessRetreatsRoute: typeof WellnessRetreatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handpan-classes': {
      id: '/handpan-classes'
      path: '/handpan-classes'
      fullPath: '/handpan-classes'
      preLoaderRoute: typeof HandpanClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-healing-initiation': {
      id: '/sound-healing-initiation'
      path: '/sound-healing-initiation'
      fullPath: '/sound-healing-initiation'
      preLoaderRoute: typeof SoundHealingInitiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-healing-sessions': {
      id: '/sound-healing-sessions'
      path: '/sound-healing-sessions'
      fullPath: '/sound-healing-sessions'
      preLoaderRoute: typeof SoundHealingSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness-retreats': {
      id: '/wellness-retreats'
      path: '/wellness-retreats'
      fullPath: '/wellness-retreats'
      preLoaderRoute: typeof WellnessRetreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HandpanClassesRoute: HandpanClassesRoute,
  SoundHealingInitiationRoute: SoundHealingInitiationRoute,
  SoundHealingSessionsRoute: SoundHealingSessionsRoute,
  WellnessRetreatsRoute: WellnessRetreatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
